(source "gnu"   "http://elpa.emacs-china.org/gnu/")
(source "melpa" "http://elpa.emacs-china.org/melpa/")

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "doom-themes")
(depends-on "doom-modeline")
(depends-on "neotree")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "ivy")
(depends-on "helm")
(depends-on "swiper")
(depends-on "counsel")
(depends-on "company")
(depends-on "diredx")
